[project]
name = "elixir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "packaging>=25.0",
    "requests>=2.32.5",
]
