name: E2E tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  e2e_tests:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ubuntu-20.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install vfox (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
          sudo apt-get update
          sudo apt-get install vfox
      
      - name: install vfox (MacOS)
        if: runner.os == 'MacOS'
        run: |
          brew tap version-fox/tap
          brew install vfox
      
      - name: add vfox-erlang & vfox-elixir plugin
        run: |
          vfox add --source https://github.com/version-fox/vfox-erlang/archive/refs/heads/main.zip erlang
          vfox add --source https://github.com/version-fox/vfox-elixir/archive/refs/heads/main.zip elixir

      - name: install Erlang/OTP & Elixir by vfox-erlang & vfox-elixir plugin (Darwin)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk
          vfox install erlang@26.2.3
          vfox use -g erlang@26.2.3
          eval "$(vfox activate bash)"
          which erl 
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          vfox install elixir@1.16.2
          vfox use -g elixir@1.16.2
          elixirc -v
          elixir hello.ex

      - name: install Erlang/OTP & Elixir by vfox-erlang & vfox-elixir plugin (Darwin)
        if: runner.os == 'MacOS'
        run: |
          brew install autoconf libxslt fop wxwidgets openssl
          vfox install erlang@26.2.3
          vfox use -g erlang@26.2.3
          eval "$(vfox activate bash)"
          which erl 
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          vfox install elixir@1.16.2
          vfox use -g elixir@1.16.2
          elixirc -v
          elixir hello.ex
          